[features]
seeds = false
[programs.devnet]
myepicproject = "5jydopMTBGQrwWJvpWRnw8JDUPPrARjHAtjCrjzqbSp1"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/peace/.config/solana/id.json"

[scripts]
test = "yarn run mocha -t 1000000 tests/"
